import pandas as pd
import numpy as np

# 1. Load U.S. News Data
df_usnews = pd.read_excel('Data/US-News-National-University-Rankings-Top-150-Through-2026.xlsx')

# Load IPEDS Public University mapping (generated from R)
df_public = pd.read_csv('Data/ipeds_public_universities.csv')

# Standardize IDs for merging
df_usnews['IPEDS'] = pd.to_numeric(df_usnews['IPEDS'], errors='coerce')
df_public['unitid'] = pd.to_numeric(df_public['unitid'], errors='coerce')

# Filter for only 4-year Public institutions offering bachelor's degrees or above
# ipeds_public_universities.csv was generated by export_public_ipeds.R with:
#   control == 1  (Public)
#   iclevel == 1  (Four-or-more year institution)
#   hloffer >= 5  (Highest offering is Bachelor's or above)
#   deggrant == 1 (Confirmed degree-granting status)
df_public_usnews = pd.merge(df_usnews, df_public, left_on='IPEDS', right_on='unitid', how='inner')

# 3. Reshape and Aggregate
# Target years: 2012-2024
year_cols = [str(y) for y in range(2012, 2025)]
df_long = df_public_usnews.melt(id_vars=['stabbr', 'University Name'], 
                                value_vars=year_cols, 
                                var_name='year', 
                                value_name='rank')

# Ensure rank is numeric
df_long['rank'] = pd.to_numeric(df_long['rank'], errors='coerce')
df_long = df_long.dropna(subset=['rank'])

# Define state-year groupings
# Count number of public universities in Top 10th percentile brackets (10, 20, ..., 150)
def calculate_tiers(x):
    thresholds = range(10, 160, 10)
    return pd.Series({f'top_{t}': (x['rank'] <= t).sum() for t in thresholds})

df_caliber = df_long.groupby(['stabbr', 'year']).apply(calculate_tiers).reset_index()

# Forward-fill 2024 results to 2025 and 2026 (for the full longitudinal study period)
df_2024 = df_caliber[df_caliber['year'] == '2024']
if not df_2024.empty:
    df_2025 = df_2024.copy(); df_2025['year'] = '2025'
    df_2026 = df_2024.copy(); df_2026['year'] = '2026'
    df_caliber = pd.concat([df_caliber, df_2025, df_2026], ignore_index=True)

# Save to Output folder
df_caliber.to_csv('Output/us_news_caliber_panel.csv', index=False)
print(f"Success! US News caliber panel saved to Output/us_news_caliber_panel.csv")
print(f"Total entries: {len(df_caliber)}")
